import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import{NavbarDemo} from './Navbar/navbarmanue'
import { NavbarDemo } from "../components/Navbar/nav";
import Header from "../components/NewNav/page";
import { NavBarSection } from "../components/HeroNavbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" className="dark text-foreground bg-background">
         <body className={inter.className}>
            {/* <Header /> */}
            {children}
         </body>
      </html>
   );
}
